
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  host: <%= ENV.fetch("DB_HOST") %>
  password: password

development:
  <<: *default
  database: workshop_treinadev_development
 
test:
  <<: *default
  database: workshop_treinadev_test

production:
  <<: *default
  database: workshop_treinadev_production
  username: workshop_treinadev
  password: <%= ENV['WORKSHOP_TREINADEV_DATABASE_PASSWORD'] %>
